/**
 * The various log modes
 */
export type LogType = 'base' | 'command' | 'mongo' | 'expectedCollections' | 'actualCollections';
/**
 * An array of [[LogType]]
 */
export type LogTypes = LogType[];

/**
 * The options about what will be logged during the function execution
 */
export interface LogOptions {
    /**
     * If nothing will be logged.
     *
     * Default: false
     */
    silent?: boolean;
    /**
     * The log modes. If there is more than a mode, they must be specified in an array.
     *
     * Possible values:
     * - 'base': During exporting, the databases and collections are shown with a spinner.
     * - 'command': Logs the mongoexport/mongodump command
     * - 'mongo': Logs the mongoexport/mongodump log
     * - 'expectedCollections': Logs the object containing the collections expected to be exported
     * - 'actualCollections': Logs the object containing the collections that have actually been exported
     *
     * Default: ['base']
     */
    log?: LogTypes | LogType;
    /**
     * If the `mongoexport` log is specified, it will show the actual log generated by mongoexport under the hood.
     * If this option is true, this log will be shown in realtime, during the exporting operation. If it is false, it will be
     * shown in the end of the exporting operation.
     *
     * Default: false
     */
    realtimeLog?: boolean;
}
