name: Lint
on: [push]

jobs:
  test:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Lint source code
        run: npm run lint:source
      
      - name: Lint test code
        run: npm run lint:test
