name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
        mongodb-version: [4.4]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Use MongoDB ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Transpile code
        run: npm run transpile
      
      - name: Populate db
        run: npm run db:populate
        
      - name: Test and generate coverage report
        run: npm run nyc
      
      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Send coverage report to Codecov
        uses: Atrox/codecov-action@v0.1.2
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} 
      
      - name: Send coverage report to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 
